# -*- coding: utf-8 -*-
"""chatbot_app.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1kQfnaNeuSZcLteXEMzYNCtpH5s_E9Fur
"""

pip install streamlit langchain langchain-google-genai python-dotenv

import streamlit as st
import os

from langchain_core.prompts import ChatPromptTemplate
from langchain_core.output_parsers import StrOutputParser
from langchain_google_genai import ChatGoogleGenerativeAI



os.environ["GOOGLE_API_KEY"] = "AIzaSyAs19tt0iF7iDZsJv_hij8CH7Ow-76K-OY"



llm = ChatGoogleGenerativeAI(
    model="gemini-2.5-flash",
    temperature=0.7
)



roles = {
    "Helpful Assistant": "You are a helpful AI assistant.",
    "Curious Teacher": "You are a curious teacher who asks questions back to the user.",
    "Advanced Vocabulary": "Respond using sophisticated vocabulary and formal tone.",
    "Brief Assistant": "Always respond in very short answers."
}



st.title("Role Based LLM Chatbot")

selected_role = st.selectbox("Choose chatbot role", list(roles.keys()))

system_message = roles[selected_role]



if "chat_history" not in st.session_state:
    st.session_state.chat_history = []



prompt = ChatPromptTemplate.from_messages(
[
    ("system", system_message),
    ("placeholder", "{chat_history}"),
    ("human", "{input}")
]
)

parser = StrOutputParser()

chain = prompt | llm | parser



user_input = st.chat_input("Ask something...")

if user_input:

    st.session_state.chat_history.append(("human", user_input))

    response = chain.invoke({
        "chat_history": st.session_state.chat_history,
        "input": user_input
    })

    st.session_state.chat_history.append(("ai", response))



for role, message in st.session_state.chat_history:

    if role == "human":
        st.chat_message("user").write(message)
    else:
        st.chat_message("assistant").write(message)